const fs = require('fs');

const filesToFix = [
  'src/app/admin/newsfeed/page.tsx',
  'src/app/admin/page.tsx',
  'src/app/admin/phone/batches/page.tsx',
  'src/app/admin/phone/list/page.tsx',
  'src/app/admin/staff/page.tsx',
  'src/app/admin/stats/report/page.tsx',
  'src/app/admin/tasks/page.tsx',
  'src/components/admin/MailManagement.tsx'
];

// Từ điển sửa lỗi font (Mojibake -> UTF-8 chuẩn)
const dictionary = {
  // Uppercase
  'QUáº¢N LÃ\\x9d': 'QUẢN LÝ',
  'QUáº¢N LÃ': 'QUẢN LÝ',
  'NHÃ\\x82N Sá»°': 'NHÂN SỰ',
  'NHÃ‚N Sá»°': 'NHÂN SỰ',
  'CÃ\\x94NG VIá»\\x86C': 'CÔNG VIỆC',
  'CÃ”NG VIá»†C': 'CÔNG VIỆC',
  'NHÃ\\x82N VIÃ\\x8aN': 'NHÂN VIÊN',
  'NHÃ‚N VIÃŠN': 'NHÂN VIÊN',
  'THá»\\xac VIá»\\x86C': 'THỬ VIỆC',
  'THá»¬ VIá»†C': 'THỬ VIỆC',
  'Ä\\x90Ä\\x83ng KÃ½': 'Đăng Ký',
  'ÄÄƒng KÃ½': 'Đăng Ký',
  'TOÃ\\x80N Bá»\\x98': 'TOÀN BỘ',
  'TOÃ\u0080N Bá»\u0098': 'TOÀN BỘ',

  // Common mixed
  'KhÃ´ng cÃ³': 'Không có',
  'khÃ´ng cÃ³': 'không có',
  'thÃ´ng bÃ¡o': 'thông báo',
  'ThÃ´ng bÃ¡o': 'Thông báo',
  'NhÃ¢n viÃªn': 'Nhân viên',
  'nhÃ¢n viÃªn': 'nhân viên',
  'hệ thá»‘ng': 'hệ thống',
  'há»‡ thá»‘ng': 'hệ thống',
  'Ä‘ang': 'đang',
  'Ä\\x91ang': 'đang',
  'xin phÃ©p': 'xin phép',
  'vÃ\\xa0o': 'vào',
  'vÃ o': 'vào',
  'tÃ\\xa0i khoáº£n': 'tài khoản',
  'tÃ i khoáº£n': 'tài khoản',
  'Ä‘Ã£': 'đã',
  'Ä\\x90Ã£': 'Đã',
  'ÄÃ£': 'Đã',
  'Ä‘á»\\x8dc': 'đọc',
  'Ä‘á»c': 'đọc',
  'táº¥t cáº£': 'tất cả',
  'má»›i': 'mới',
  'NgÆ°á»\\x9di dÃ¹ng': 'Người dùng',
  'NgÆ°á»i dÃ¹ng': 'Người dùng',
  'Há»\\x93 sÆ¡': 'Hồ sơ',
  'Há»“ sÆ¡': 'Hồ sơ',
  'chi tiáº¿t': 'chi tiết',
  'Ä\\x90Ä\\x83ng xuáº¥t': 'Đăng xuất',
  'ÄÄƒng xuáº¥t': 'Đăng xuất',
  'Trung tÃ¢m': 'Trung tâm',
  'ChÆ°a': 'Chưa',
  'Ä\\x90Ã¡nh dáº¥u': 'Đánh dấu',
  'ÄÃ¡nh dáº¥u': 'Đánh dấu',
  'má»\\xa5c nÃ\\xa0y': 'mục này',
  'má»¥c nÃ y': 'mục này',
  'Duyá»‡t': 'Duyệt',
  'PhÃª duyá»‡t': 'Phê duyệt',
  'quyá»\\x81n': 'quyền',
  'quyá»n': 'quyền',
  'truy cáº\\xadp': 'truy cập',
  'truy cáº­p': 'truy cập',
  'Há»\\x8d vÃ\\xa0 tÃªn': 'Họ và tên',
  'Há» vÃ  tÃªn': 'Họ và tên',
  'TÃªn': 'Tên',
  'Ä‘Ä\\x83ng nháº\\xadt': 'đăng nhập',
  'Ä‘Äƒng nháº­p': 'đăng nhập',
  'Sá»\\x91': 'Số',
  'Sá»‘': 'Số',
  'Ä‘iá»‡n thoáº¡i': 'điện thoại',
  'NÄ\\x83m sinh': 'Năm sinh',
  'NÄƒm sinh': 'Năm sinh',
  'Ä\\x90á»‹a chá»\\x89': 'Địa chỉ',
  'Äá»‹a chá»‰': 'Địa chỉ',
  'Chá»\\x8dn': 'Chọn',
  'Chá»n': 'Chọn',
  'chá»©c vá»\\xa5': 'chức vụ',
  'chá»©c vá»¥': 'chức vụ',
  'Tá»« chá»‘i': 'Từ chối',
  'Ä\\x90á»\\x93ng Ã½': 'Đồng ý',
  'Äá»“ng Ã½': 'Đồng ý',
  'Quáº£n trá»‹': 'Quản trị',
  'Tráº¡ng thÃ¡i': 'Trạng thái',
  'tráº¡ng thÃ¡i': 'trạng thái',
  'cáº\\xadp nháº\\xadt': 'cập nhật',
  'cáº­p nháº­t': 'cập nhật',
  'Lá»\\x97i': 'Lỗi',
  'Lá»—i': 'Lỗi',
  'tá»± Ä‘á»™ng': 'tự động',
  'lÃ´': 'lô',
  'vá»‡ tinh': 'vệ tinh',
  'thÃ\\xa0nh cÃ´ng': 'thành công',
  'thÃ nh cÃ´ng': 'thành công',
  'vÃ\\xa0o': 'vào',
  'kÃ¡ÂºÂ¿t nÃ¡Â»â€˜i': 'kết nối',
  'KhÃƒÂ´ng thÃ¡Â»Æ’': 'Không thể',
  'lÃ†Â°u': 'lưu',
  'lÆ°u': 'lưu',
  'Ä‘Æ°á»£c': 'được',
  'giao': 'giao',
  'Ä‘á»ƒ': 'để',
  'xÃ¡c minh': 'xác minh',
  'trong ngÃ\\xa0y': 'trong ngày',
  'trong ngÃ y': 'trong ngày',
  'Tiáº¿n Ä‘á»™': 'Tiến độ',
  'cÃ´ng viá»‡c': 'công việc',
  'Lá»\\x8dc': 'Lọc',
  'Lá»c': 'Lọc',
  'Táº¥t cáº£': 'Tất cả',
  'NgÃ\\xa0y': 'Ngày',
  'NgÃ y': 'Ngày',
  'bÃ\\xa0n giao': 'bàn giao',
  'bÃ n giao': 'bàn giao',
  'hiá»‡n táº¡i': 'hiện tại',
  'Thao tÃ¡c': 'Thao tác',
  'lÃ\\xa0m': 'làm',
  'lÃ m': 'làm',
  'láº§n': 'lần',
  'BÃ¡o': 'Báo',
  'khá»›p': 'khớp',
  'tÃ¬m kiáº¿m': 'tìm kiếm',
  'bÃ¡n': 'bán',
  'Ä‘iá»n': 'điền',
  'Ä‘á»§': 'đủ',
  'kÃªnh': 'kênh',
  'trÆ°á»›c khi': 'trước khi',
  'chuyá»ƒn': 'chuyển',
  'giao diá»‡n': 'giao diện',
  'xáº£y ra': 'xảy ra',
  'hoÃ\\xa0n thÃ\\xa0nh': 'hoàn thành',
  'hoÃ n thÃ nh': 'hoàn thành',
  'quÃ©t': 'quét',
  'XÃ¡c nhÃ¢n': 'Xác nhận',
  'XÃ¡c nháº­n': 'Xác nhận',
  'xÃ³a': 'xóa',
  'Báº¡n': 'Bạn',
  'cháº¯c chắn': 'chắc chắn',
  'cháº¯c cháº¯n': 'chắc chắn',
  'muá»‘n': 'muốn',
  'hÃºy bá»': 'hủy bỏ',
  'HÃºy bá»': 'Hủy bỏ',
  'Hủy bá»': 'Hủy bỏ',
  'Hủy bá»\\x8f': 'Hủy bỏ',
  'Hủy bá»\x8f': 'Hủy bỏ',
  'tÃ\\xa0i liá»‡u': 'tài liệu',
  'dÃ²ng': 'dòng',
  'lịch sá»\\xad': 'lịch sử',
  'lịch sá»ử': 'lịch sử',
  'lịch sá»­': 'lịch sử',
  'Gá»‘c': 'Gốc',
  'Vá»‡ Tinh': 'Vệ Tinh',
  'Báº­t Kiáº¿m Tiá»n': 'Bật Kiếm Tiền',
  'dá»¯ liá»‡u': 'dữ liệu',
  'cá»§a': 'của',
  'Báº¥m vÃ\\xa0o': 'Bấm vào',
  'Báº¥m vÃ o': 'Bấm vào',
  'xá»\\xad lÃ½': 'xử lý',
  'xá»­ lÃ½': 'xử lý',
  'cÃ¡c': 'các',
  'Quay láº¡i': 'Quay lại',
  'gÃ¡n': 'gán',
  'Máº­t kháº©u': 'Mật khẩu',
  'Trá»Ÿ vá»\\x81': 'Trở về',
  'Trá»Ÿ vá»': 'Trở về',
  'tÃ¡i': 'tái',
  'khÃ´i phá»¥c': 'khôi phục',
  'Ä‘Æ°a': 'đưa',
  'Ä‘Ã¡nh giÃ¡': 'đánh giá',
  'Báº£ng': 'Bảng',
  'LÆ°Æ¡ng': 'Lương',
  'Hiá»‡u': 'Hiệu',
  'Suáº¥t': 'Suất',
  'thÃ¡ng': 'tháng',
  'gáº§n Ä‘Ã¢y': 'gần đây',
  'MÃ£': 'Mã',
  'NhÃ¢n viÃªn': 'Nhân viên',
  'KÃªnh': 'Kênh',
  'Ä‘á»§ giá»\\x9d': 'đủ giờ',
  'Ä‘á»§ giá»': 'đủ giờ',
  'Ä‘á»§ giá»': 'đủ giờ',
  'Ä‘áº¡t': 'đạt',
  'Tá»•ng': 'Tổng',
  'ThÆ°á»Ÿng': 'Thưởng',
  'Pháº¡t': 'Phạt',
  'Thá»±c lÃ£nh': 'Thực lãnh',
  'Xuáº¥t Excel': 'Xuất Excel',
  'xuáº¥t': 'xuất',
  'MÃ\\xa0n hÃ¬nh': 'Màn hình',
  'MÃ n hÃ¬nh': 'Màn hình',
  'KhÃ³a': 'Khóa',
  'Táº¡m': 'Tạm',
  'Mở': 'Mở',
  'TÃ¹y': 'Tùy',
  'Chá»‰nh': 'Chỉnh',
  'TrÆ°á»›c': 'Trước',
  'Sau': 'Sau',
  'ÄÃºng': 'Đúng',
  'Sai': 'Sai',
  'VÃ\\xa0': 'Và',
  'VÃ ': 'Và',
  'Hoáº·c': 'Hoặc',
  'Thay Ä‘á»•i': 'Thay đổi',
  'ThÃªm': 'Thêm',
  'Sá»a': 'Sửa',
  'LÆ°u': 'Lưu',
  'ThÃ´ng': 'Thông',
  'BÃ¡o': 'Báo',
  'CÃ¡o': 'Cáo',
  'Káº¿t': 'Kết',
  'Quáº£': 'Quả',
  'Báº¯t Ä‘áº§u': 'Bắt đầu',
  'Káº¿t thÃºc': 'Kết thúc',
  'NgÆ°á»i': 'Người',
  'DÃ¹ng': 'Dùng',
  'Chá»©c': 'Chức',
  'Vá»¥': 'Vụ',
  'Trang': 'Trang',
  'Chá»§': 'Chủ',
  'Quáº£n': 'Quản',
  'LÃ½': 'Lý',
  'NhÃ¢n': 'Nhân',
  'Sá»±': 'Sự',
  'CÃ´ng': 'Công',
  'Viá»‡c': 'Việc',
  'CÃ¡i': 'Cái',
  'Äáº·t': 'Đặt',
  'Äá»ƒ': 'Để',
  'LÃ\\xa0m': 'Làm',
  'LÃ m': 'Làm',
  'GÃ¬': 'Gì',
  'ÄÃ³': 'Đó',
  'thÃ¬': 'thì',
  'lÃ\\xa0': 'là',
  'lÃ ': 'là',
  'cÃ³': 'có',
  'Ä‘Æ°á»£c': 'được',
  'khÃ´ng': 'không',
  'pháº£i': 'phải',
  'cá»§a': 'của',
  'tÃ´i': 'tôi',
  'báº¡n': 'bạn',
  'chÃºng': 'chúng',
  'ta': 'ta',
  'Há»‡': 'Hệ',
  'Thá»‘ng': 'Thống',
  'Äang': 'Đang',
  'Xá»': 'Xử',
  'LÃ½': 'Lý',
  'YÃªu': 'Yêu',
  'Cáº§u': 'Cầu',
  'truy': 'truy',
  'cáº­p': 'cập',
  'ngoÃ\\xa0i': 'ngoài',
  'ngoÃ i': 'ngoài',
  'giá»\\x9d': 'giờ',
  'giá»': 'giờ',
  'giá»': 'giờ',
  'phÃ©p': 'phép',
  'LÃ\\x9d': 'LÝ',
  'LÃ': 'LÝ',
  'Tá»ª': 'TỪ',
  'CHá»\\x90I': 'CHỐI',
  'CHá»I': 'CHỐI',
  'Ä\\x90á»\\x92NG': 'ĐỒNG',
  'Äá»’NG': 'ĐỒNG',
  'Ã\\x9d': 'Ý',
  'Ã': 'Ý',
  
  // Custom manual mappings often found in encoded react files
  'NhÃƒÂ¢n viÃƒÂªn': 'Nhân viên',
  'há»‡ thá»‘ng': 'hệ thống',
  'Thá»i gian': 'Thời gian',
  'NhÃ¢n viÃªn thá»­ viá»‡c': 'Nhân viên thử việc',
  'PhÃª duyá»‡t quyá»n truy cáº­p': 'Phê duyệt quyền truy cập',
  'TÃªn Ä‘Äƒng nháº­p': 'Tên đăng nhập',
  'Sá»‘ Ä‘iá»‡n thoáº¡i': 'Số điện thoại',
  'NÄƒm sinh': 'Năm sinh',
  'Chá»n chá»©c vá»¥': 'Chọn chức vụ',
  'PhÃª duyá»‡t & Äá»“ng Ã½': 'Phê duyệt & Đồng ý',
  'Xem chi tiáº¿t táº¡i trang Quáº£n trá»‹ NhÃ¢n sá»±': 'Xem chi tiết tại trang Quản trị Nhân sự',
  'QUáº¢N LÃ CÃ”NG VIá»†C': 'QUẢN LÝ CÔNG VIỆC',
  'QL CÃ”NG VIá»†C': 'QL CÔNG VIỆC',
  'QUáº¢N LÃ NHÃ‚N Sá»°': 'QUẢN LÝ NHÂN SỰ',
  'QL NHÃ‚N Sá»°': 'QL NHÂN SỰ',
  'NHÃ‚N VIÃŠN': 'NHÂN VIÊN'
};

filesToFix.forEach(file => {
  if (fs.existsSync(file)) {
    let content = fs.readFileSync(file, 'utf8');
    let original = content;
    
    // Pass 1: Defined Dictionary
    for (const [key, value] of Object.entries(dictionary)) {
      content = content.split(key).join(value);
    }
    
    // Pass 2: Generalized Regex for leftover single characters
    content = content.replace(/Ã\\x81|Ã\\x82|Ã\\x83|Ã\\x84|Ã\\x85|Ã\\x86|Ã\\x87|Ã\\x88|Ã\\x89|Ã\\x8a|Ã\\x8b|Ã\\x8c|Ã\\x8d|Ã\\x8e|Ã\\x8f|Ã\\x90|Ã\\x91|Ã\\x92|Ã\\x93|Ã\\x94|Ã\\x95|Ã\\x96|Ã\\x97|Ã\\x98|Ã\\x99|Ã\\x9a|Ã\\x9b|Ã\\x9c|Ã\\x9d|Ã\\x9e|Ã\\x9f|Ã\\xa0|Ã\\xa1|Ã\\xa2|Ã\\xa3|Ã\\xa4|Ã\\xa5|Ã\\xa6|Ã\\xa7|Ã\\xa8|Ã\\xa9|Ã\\xaa|Ã\\xab|Ã\\xac|Ã\\xad|Ã\\xae|Ã\\xaf|Ã\\xb0|Ã\\xb1|Ã\\xb2|Ã\\xb3|Ã\\xb4|Ã\\xb5|Ã\\xb6|Ã\\xb7|Ã\\xb8|Ã\\xb9|Ã\\xba|Ã\\xbb|Ã\\xbc|Ã\\xbd|Ã\\xbe|Ã\\xbf|Ä\\x80|Ä\\x81|Ä\\x82|Ä\\x83|Ä\\x84|Ä\\x85|Ä\\x86|Ä\\x87|Ä\\x88|Ä\\x89|Ä\\x8a|Ä\\x8b|Ä\\x8c|Ä\\x8d|Ä\\x8e|Ä\\x8f|Ä\\x90|Ä\\x91|Ä\\x92|Ä\\x93|Ä\\x94|Ä\\x95|Ä\\x96|Ä\\x97|Ä\\x98|Ä\\x99|Ä\\x9a|Ä\\x9b|Ä\\x9c|Ä\\x9d|Ä\\x9e|Ä\\x9f|Ä\\xa0|Ä\\xa1|Ä\\xa2|Ä\\xa3|Ä\\xa4|Ä\\xa5|Ä\\xa6|Ä\\xa7|Ä\\xa8|Ä\\xa9|Ä\\xaa|Ä\\xab|Ä\\xac|Ä\\xad|Ä\\xae|Ä\\xaf|Ä\\xb0|Ä\\xb1|Ä\\xb2|Ä\\xb3|Ä\\xb4|Ä\\xb5|Ä\\xb6|Ä\\xb7|Ä\\xb8|Ä\\xb9|Ä\\xba|Ä\\xbb|Ä\\xbc|Ä\\xbd|Ä\\xbe|Ä\\xbf/g, (match) => {
        try {
            return decodeURIComponent(escape(match));
        } catch(e) {
            return match;
        }
    });

    if (content !== original) {
      fs.writeFileSync(file, content, 'utf8');
      console.log('Fixed:', file);
    }
  }
});
console.log('Global Mojibake Fix Complete.');
